// GENERATED BY gen.py -- do not hand-edit; edit build.py data and re-run.
const IMAGE_ORDER = [
  "heart_internal",
  "heart_surface_ant",
  "heart_surface_post",
  "heart_valves",
  "heart_conduction",
  "blood_formed",
  "vessel_cutaway",
  "vessel_cross",
  "cardiac_dia",
  "cardiac_histo",
  "heart_wall",
  "resp_overview",
  "resp_upper",
  "resp_larynx",
  "resp_lungs",
  "resp_alveoli",
  "resp_trachea_histo",
  "resp_pleura",
  "resp_muscles"
];

const IMAGE_DATA = {
  "heart_internal": {
    "src": "images/heart_internal.jpg",
    "title": "Station 1 \u00b7 Heart \u2014 Chambers & Internal Anatomy",
    "caption": "Heart \u2014 frontal (coronal) section, anterior view",
    "words": [
      "Aorta (ascending)",
      "Bicuspid (mitral) valve",
      "Chordae tendineae",
      "Endocardium",
      "Epicardium",
      "Inferior vena cava",
      "Interventricular septum",
      "Left atrium",
      "Left pulmonary artery",
      "Left pulmonary veins",
      "Left ventricle",
      "Myocardium",
      "Papillary muscle",
      "Pulmonary trunk",
      "Right atrium",
      "Right pulmonary artery",
      "Right pulmonary veins",
      "Right ventricle",
      "Superior vena cava",
      "Trabeculae carneae",
      "Tricuspid valve"
    ],
    "size": [
      666,
      717
    ]
  },
  "heart_surface_ant": {
    "src": "images/heart_surface_ant.jpg",
    "title": "Station 2 \u00b7 Heart \u2014 Surface & Great Vessels (anterior)",
    "caption": "Heart \u2014 external surface, anterior view",
    "words": [
      "Anterior interventricular artery",
      "Aortic arch",
      "Apex of heart",
      "Ascending aorta",
      "Auricle of left atrium",
      "Great cardiac vein",
      "Left coronary artery",
      "Ligamentum arteriosum",
      "Right auricle",
      "Right coronary artery"
    ],
    "size": [
      538,
      554
    ]
  },
  "heart_surface_post": {
    "src": "images/heart_surface_post.jpg",
    "title": "Station 3 \u00b7 Heart \u2014 Surface & Great Vessels (posterior)",
    "caption": "Heart \u2014 external surface, posterior view",
    "words": [
      "Coronary sinus",
      "Middle cardiac vein",
      "Posterior interventricular artery"
    ],
    "size": [
      525,
      578
    ]
  },
  "heart_valves": {
    "src": "images/heart_valves.jpg",
    "title": "Station 4 \u00b7 Heart Valves",
    "caption": "Heart valves \u2014 superior view (atria removed)",
    "words": [
      "Aortic semilunar valve",
      "Bicuspid (mitral) valve",
      "Pulmonary semilunar valve",
      "Tricuspid valve"
    ],
    "size": [
      972,
      643
    ]
  },
  "heart_conduction": {
    "src": "images/heart_conduction.jpg",
    "title": "Station 5 \u00b7 Cardiac Conduction System",
    "caption": "Cardiac conduction system \u2014 anterior view of frontal section",
    "words": [
      "Atrioventricular (AV) node",
      "Atrioventricular bundle (bundle of His)",
      "Purkinje fibers",
      "Right and left bundle branches",
      "Sinoatrial (SA) node"
    ],
    "size": [
      615,
      773
    ]
  },
  "blood_formed": {
    "src": "images/blood_formed.jpg",
    "title": "Station 6 \u00b7 Blood \u2014 Formed Elements",
    "caption": "Blood smear \u2014 formed elements (slide #16)",
    "words": [
      "Basophil",
      "Eosinophil",
      "Erythrocytes",
      "Lymphocyte",
      "Monocyte",
      "Neutrophil",
      "Platelets"
    ],
    "size": [
      1280,
      960
    ]
  },
  "vessel_cutaway": {
    "src": "images/vessel_cutaway.jpg",
    "title": "Station 7 \u00b7 Blood Vessel \u2014 Wall Layers",
    "caption": "Artery wall \u2014 layers (slide #3, Artery/Vein/Nerve)",
    "words": [
      "Endothelium",
      "Internal elastic lamina",
      "Tunica externa",
      "Tunica media"
    ],
    "size": [
      691,
      666
    ]
  },
  "vessel_cross": {
    "src": "images/vessel_cross.jpg",
    "title": "Station 8 \u00b7 Blood Vessel \u2014 Cross-Section",
    "caption": "Artery \u2014 cross-section (slide #3)",
    "words": [
      "Lumen",
      "Tunica interna (intima)"
    ],
    "size": [
      460,
      486
    ]
  },
  "cardiac_dia": {
    "src": "images/cardiac_dia.jpg",
    "title": "Station 9 \u00b7 Cardiac Muscle \u2014 Intercalated Discs",
    "caption": "Cardiac muscle \u2014 intercalated discs (slide #45)",
    "words": [
      "Intercalated disc",
      "Myofiber"
    ],
    "size": [
      384,
      540
    ]
  },
  "cardiac_histo": {
    "src": "images/cardiac_histo.jpg",
    "title": "Station 10 \u00b7 Cardiac Muscle \u2014 Histology (Slide 45)",
    "caption": "Cardiac muscle \u2014 histology (slide #45)",
    "words": [
      "Myofiber",
      "Nucleus (central)",
      "Striations"
    ],
    "size": [
      769,
      590
    ]
  },
  "heart_wall": {
    "src": "images/heart_wall.jpg",
    "title": "Station 11 \u00b7 Heart Wall & Pericardium",
    "caption": "Heart wall & pericardium \u2014 layered detail",
    "words": [
      "Endocardium",
      "Epicardium (visceral serous pericardium)",
      "Fibrous pericardium",
      "Myocardium",
      "Parietal layer of serous pericardium",
      "Pericardial cavity"
    ],
    "size": [
      796,
      783
    ]
  },
  "resp_overview": {
    "src": "images/resp_overview.jpg",
    "title": "Station 12 \u00b7 Respiratory System Overview",
    "caption": "Respiratory system \u2014 overview",
    "words": [
      "Diaphragm",
      "Larynx",
      "Lung",
      "Main (primary) bronchus",
      "Nasal cavity",
      "Pharynx",
      "Trachea"
    ],
    "size": [
      537,
      914
    ]
  },
  "resp_upper": {
    "src": "images/resp_upper.jpg",
    "title": "Station 13 \u00b7 Upper Airway \u2014 Nasal Cavity & Pharynx",
    "caption": "Upper airway \u2014 nasal cavity & pharynx (sagittal section)",
    "words": [
      "Cricoid cartilage",
      "Epiglottis",
      "External nares (nostril)",
      "Glottis",
      "Hard palate",
      "Laryngopharynx",
      "Nasal conchae",
      "Nasal meatus",
      "Nasal vestibule",
      "Nasopharynx",
      "Opening of auditory (pharyngotympanic) tube",
      "Oropharynx",
      "Soft palate",
      "Thyroid cartilage",
      "Trachea",
      "Uvula",
      "Vocal fold (vocal cords)"
    ],
    "size": [
      589,
      1004
    ]
  },
  "resp_larynx": {
    "src": "images/resp_larynx.jpg",
    "title": "Station 14 \u00b7 Larynx",
    "caption": "Larynx \u2014 anterior view",
    "words": [
      "Cricoid cartilage",
      "Cricothyroid ligament",
      "Epiglottis",
      "Thyroid cartilage",
      "Tracheal cartilages"
    ],
    "size": [
      384,
      484
    ]
  },
  "resp_lungs": {
    "src": "images/resp_lungs.jpg",
    "title": "Station 15 \u00b7 Lungs \u2014 Lobes & Bronchial Tree",
    "caption": "Lungs \u2014 lobes & bronchial tree",
    "words": [
      "Carina",
      "Left inferior lobe",
      "Left superior lobe",
      "Lobar (secondary) bronchus",
      "Main (primary) bronchus",
      "Right inferior lobe",
      "Right middle lobe",
      "Right superior lobe",
      "Segmental (tertiary) bronchus",
      "Trachea"
    ],
    "size": [
      922,
      783
    ]
  },
  "resp_alveoli": {
    "src": "images/resp_alveoli.jpg",
    "title": "Station 16 \u00b7 Alveoli \u2014 Lung Histology",
    "caption": "Alveoli \u2014 lung histology",
    "words": [
      "Alveolar duct / sac",
      "Alveolus",
      "Pulmonary arteriole",
      "Pulmonary venule",
      "Respiratory bronchiole"
    ],
    "size": [
      383,
      305
    ]
  },
  "resp_trachea_histo": {
    "src": "images/resp_trachea_histo.jpg",
    "title": "Station 17 \u00b7 Trachea \u2014 Histology",
    "caption": "Trachea wall \u2014 histology (slide #9)",
    "words": [
      "Cilia",
      "Goblet cell",
      "Mucosa",
      "Pseudostratified ciliated columnar epithelium",
      "Tracheal (seromucous) glands"
    ],
    "size": [
      998,
      548
    ]
  },
  "resp_pleura": {
    "src": "images/resp_pleura.jpg",
    "title": "Station 18 \u00b7 Pleural Membranes",
    "caption": "Pleural membranes (detail)",
    "words": [
      "Parietal pleura",
      "Pleural cavity",
      "Visceral pleura"
    ],
    "size": [
      396,
      337
    ]
  },
  "resp_muscles": {
    "src": "images/resp_muscles.jpg",
    "title": "Station 19 \u00b7 Respiratory Muscles",
    "caption": "Respiratory muscles \u2014 thoracic cavity",
    "words": [
      "Diaphragm",
      "Intercostal muscles"
    ],
    "size": [
      512,
      810
    ]
  }
};

// Pre-verified answer key. Loaded on first run; the teacher can
// re-pin anything and Save to override it in localStorage.
const PRESET_KEYS = {
  "heart_internal": [
    {
      "id": 1,
      "x": 40.38,
      "y": 5.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Aorta (ascending)",
      "func": "Receives oxygenated blood from the left ventricle and carries it to the systemic circulation."
    },
    {
      "id": 2,
      "x": 23.08,
      "y": 5.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Superior vena cava",
      "func": "Returns deoxygenated blood from the head, neck, and upper limbs to the right atrium."
    },
    {
      "id": 3,
      "x": 40.38,
      "y": 21.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pulmonary trunk",
      "func": "Carries deoxygenated blood from the right ventricle toward the lungs; splits into the L and R pulmonary arteries."
    },
    {
      "id": 4,
      "x": 11.54,
      "y": 32.5,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right pulmonary veins",
      "func": "Return oxygenated blood from the right lung to the left atrium."
    },
    {
      "id": 5,
      "x": 26.92,
      "y": 43.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right atrium",
      "func": "Receives deoxygenated blood from the venae cavae and coronary sinus, then pumps it to the right ventricle."
    },
    {
      "id": 6,
      "x": 34.62,
      "y": 56.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tricuspid valve",
      "func": "Right AV valve; prevents backflow from the right ventricle into the right atrium during ventricular contraction."
    },
    {
      "id": 7,
      "x": 19.23,
      "y": 63.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right ventricle",
      "func": "Pumps deoxygenated blood into the pulmonary trunk to the lungs."
    },
    {
      "id": 8,
      "x": 46.15,
      "y": 61.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Chordae tendineae",
      "func": "Fibrous cords that anchor the AV-valve cusps to the papillary muscles, preventing valve prolapse."
    },
    {
      "id": 9,
      "x": 34.62,
      "y": 73.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Trabeculae carneae",
      "func": "Muscular ridges on the internal walls of the ventricles."
    },
    {
      "id": 10,
      "x": 21.15,
      "y": 91.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Inferior vena cava",
      "func": "Returns deoxygenated blood from the trunk and lower limbs to the right atrium."
    },
    {
      "id": 11,
      "x": 67.31,
      "y": 15.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left pulmonary artery",
      "func": "Carries deoxygenated blood from the pulmonary trunk to the left lung."
    },
    {
      "id": 12,
      "x": 21.15,
      "y": 15.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right pulmonary artery",
      "func": "Carries deoxygenated blood from the pulmonary trunk to the right lung."
    },
    {
      "id": 13,
      "x": 75.0,
      "y": 28.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left atrium",
      "func": "Receives oxygenated blood from the pulmonary veins and pumps it to the left ventricle."
    },
    {
      "id": 14,
      "x": 84.62,
      "y": 32.5,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left pulmonary veins",
      "func": "Return oxygenated blood from the left lung to the left atrium."
    },
    {
      "id": 15,
      "x": 71.15,
      "y": 41.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Bicuspid (mitral) valve",
      "func": "Left AV valve; prevents backflow from the left ventricle into the left atrium."
    },
    {
      "id": 16,
      "x": 82.69,
      "y": 60.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left ventricle",
      "func": "Pumps oxygenated blood into the aorta for systemic circulation; thickest-walled chamber."
    },
    {
      "id": 17,
      "x": 67.31,
      "y": 67.5,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Papillary muscle",
      "func": "Contracts to tension the chordae tendineae, keeping the AV valves closed during ventricular systole."
    },
    {
      "id": 18,
      "x": 55.77,
      "y": 70.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Interventricular septum",
      "func": "Muscular wall that separates the right and left ventricles."
    },
    {
      "id": 19,
      "x": 96.15,
      "y": 73.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Epicardium",
      "func": "Outermost layer of the heart wall (the visceral pericardium)."
    },
    {
      "id": 20,
      "x": 90.38,
      "y": 81.25,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Myocardium",
      "func": "Thick middle layer of cardiac muscle responsible for the heart's contraction."
    },
    {
      "id": 21,
      "x": 86.54,
      "y": 87.5,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Endocardium",
      "func": "Smooth inner endothelial lining of the heart chambers and valves."
    }
  ],
  "heart_surface_ant": [
    {
      "id": 22,
      "x": 14.29,
      "y": 30.43,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Ascending aorta",
      "func": "Carries oxygenated blood from the left ventricle to the body; gives rise to the coronary arteries."
    },
    {
      "id": 23,
      "x": 47.62,
      "y": 15.22,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Aortic arch",
      "func": "Curve of the aorta that gives off the brachiocephalic, left common carotid, and left subclavian arteries."
    },
    {
      "id": 24,
      "x": 45.24,
      "y": 28.26,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Ligamentum arteriosum",
      "func": "Fetal remnant of the ductus arteriosus, connecting the pulmonary trunk to the aortic arch."
    },
    {
      "id": 25,
      "x": 57.14,
      "y": 39.13,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Auricle of left atrium",
      "func": "Ear-like flap that increases the volume capacity of the left atrium."
    },
    {
      "id": 26,
      "x": 4.76,
      "y": 39.13,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right auricle",
      "func": "Ear-like extension that increases the capacity of the right atrium."
    },
    {
      "id": 27,
      "x": 47.62,
      "y": 52.17,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left coronary artery",
      "func": "Supplies oxygenated blood to the left side of the heart; branches into the circumflex and anterior interventricular arteries."
    },
    {
      "id": 28,
      "x": 7.14,
      "y": 54.35,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right coronary artery",
      "func": "Supplies oxygenated blood to the right side of the heart."
    },
    {
      "id": 29,
      "x": 47.62,
      "y": 73.91,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Anterior interventricular artery",
      "func": "Runs in the anterior interventricular groove supplying both ventricles and the septum (the 'LAD')."
    },
    {
      "id": 30,
      "x": 52.38,
      "y": 67.39,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Great cardiac vein",
      "func": "Collects deoxygenated blood from the anterior heart and empties into the coronary sinus."
    },
    {
      "id": 31,
      "x": 42.86,
      "y": 93.48,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Apex of heart",
      "func": "Inferior pointed tip of the heart, formed by the left ventricle."
    }
  ],
  "heart_surface_post": [
    {
      "id": 32,
      "x": 43.9,
      "y": 50.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Coronary sinus",
      "func": "Large vein on the posterior heart that drains cardiac (deoxygenated) blood into the right atrium."
    },
    {
      "id": 33,
      "x": 34.15,
      "y": 75.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Middle cardiac vein",
      "func": "Drains the posterior heart and empties into the coronary sinus."
    },
    {
      "id": 34,
      "x": 39.02,
      "y": 68.75,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Posterior interventricular artery",
      "func": "Branch of the right coronary artery supplying the posterior walls of the ventricles."
    }
  ],
  "heart_valves": [
    {
      "id": 35,
      "x": 23.68,
      "y": 19.05,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tricuspid valve",
      "func": "Right AV valve; three cusps; prevents backflow from the right ventricle into the right atrium."
    },
    {
      "id": 36,
      "x": 65.79,
      "y": 15.87,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Bicuspid (mitral) valve",
      "func": "Left AV valve; two cusps; prevents backflow from the left ventricle into the left atrium."
    },
    {
      "id": 37,
      "x": 43.42,
      "y": 58.73,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Aortic semilunar valve",
      "func": "Three half-moon cusps; prevents backflow from the aorta into the left ventricle."
    },
    {
      "id": 38,
      "x": 46.05,
      "y": 92.06,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pulmonary semilunar valve",
      "func": "Three cusps; prevents backflow from the pulmonary trunk into the right ventricle."
    }
  ],
  "heart_conduction": [
    {
      "id": 39,
      "x": 22.92,
      "y": 32.22,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Sinoatrial (SA) node",
      "func": "The heart's pacemaker; initiates each heartbeat and sets the heart rate (in the right atrial wall)."
    },
    {
      "id": 40,
      "x": 27.08,
      "y": 50.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Atrioventricular (AV) node",
      "func": "Delays the impulse before it reaches the ventricles, letting the atria finish contracting first."
    },
    {
      "id": 41,
      "x": 41.67,
      "y": 54.44,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Atrioventricular bundle (bundle of His)",
      "func": "Carries the impulse from the AV node into the interventricular septum; the only electrical link between atria and ventricles."
    },
    {
      "id": 42,
      "x": 56.25,
      "y": 68.89,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right and left bundle branches",
      "func": "Conduct the impulse down either side of the interventricular septum toward the apex."
    },
    {
      "id": 43,
      "x": 62.5,
      "y": 82.22,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Purkinje fibers",
      "func": "Distribute the impulse through the ventricular myocardium, triggering ventricular contraction."
    }
  ],
  "blood_formed": [
    {
      "id": 44,
      "x": 28.0,
      "y": 22.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Erythrocytes",
      "func": "Carry oxygen (and some carbon dioxide) throughout the body using hemoglobin."
    },
    {
      "id": 45,
      "x": 72.0,
      "y": 20.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Platelets",
      "func": "Cell fragments that clot blood and stop bleeding (hemostasis)."
    },
    {
      "id": 46,
      "x": 15.0,
      "y": 60.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Monocyte",
      "func": "Largest WBC; leaves the blood to become a macrophage that phagocytizes pathogens and debris."
    },
    {
      "id": 47,
      "x": 40.0,
      "y": 62.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Lymphocyte",
      "func": "WBC of specific immunity \u2014 B cells make antibodies, T cells attack infected cells."
    },
    {
      "id": 48,
      "x": 68.0,
      "y": 55.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Eosinophil",
      "func": "Granular WBC that fights parasitic worms and moderates allergic and inflammatory responses."
    },
    {
      "id": 49,
      "x": 87.0,
      "y": 55.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Basophil",
      "func": "Granular WBC that releases histamine (inflammation) and heparin (anticoagulant) during allergic responses."
    },
    {
      "id": 50,
      "x": 77.0,
      "y": 78.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Neutrophil",
      "func": "Most abundant WBC; a first-responder that phagocytizes bacteria."
    }
  ],
  "vessel_cutaway": [
    {
      "id": 51,
      "x": 14.81,
      "y": 42.31,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tunica externa",
      "func": "Outermost vessel layer of connective tissue that anchors and protects the vessel."
    },
    {
      "id": 52,
      "x": 40.74,
      "y": 42.31,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tunica media",
      "func": "Middle layer of smooth muscle and elastic tissue that controls vessel diameter (constriction/dilation)."
    },
    {
      "id": 53,
      "x": 77.78,
      "y": 51.92,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Internal elastic lamina",
      "func": "Sheet of elastic tissue between the tunica interna and tunica media."
    },
    {
      "id": 54,
      "x": 90.74,
      "y": 30.77,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Endothelium",
      "func": "Simple squamous epithelium lining the lumen; gives a smooth, low-friction surface for blood flow."
    }
  ],
  "vessel_cross": [
    {
      "id": 55,
      "x": 66.67,
      "y": 63.16,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Lumen",
      "func": "The hollow central channel of the vessel through which blood flows."
    },
    {
      "id": 56,
      "x": 63.89,
      "y": 86.84,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tunica interna (intima)",
      "func": "Innermost layer lining the lumen; made of endothelium on a thin connective-tissue layer."
    }
  ],
  "cardiac_dia": [
    {
      "id": 57,
      "x": 65.62,
      "y": 40.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Intercalated disc",
      "func": "Junction between cardiac muscle cells; its gap junctions let the cells contract in unison."
    },
    {
      "id": 58,
      "x": 21.88,
      "y": 33.33,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Myofiber",
      "func": "A cardiac muscle cell \u2014 branched and striated, joined to neighbors by intercalated discs."
    }
  ],
  "cardiac_histo": [
    {
      "id": 59,
      "x": 66.67,
      "y": 48.89,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nucleus (central)",
      "func": "Cardiac muscle cells are usually uninucleate, with a single centrally placed nucleus."
    },
    {
      "id": 60,
      "x": 21.11,
      "y": 52.22,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Striations",
      "func": "Regular banding of overlapping actin and myosin filaments \u2014 cardiac muscle is striated."
    },
    {
      "id": 61,
      "x": 44.44,
      "y": 65.56,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Myofiber",
      "func": "A cardiac muscle cell \u2014 short, branched, and striated, joined end-to-end by intercalated discs."
    }
  ],
  "heart_wall": [
    {
      "id": 62,
      "x": 4.88,
      "y": 20.69,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Endocardium",
      "func": "Smooth inner endothelial lining of the heart chambers and valves."
    },
    {
      "id": 63,
      "x": 29.27,
      "y": 37.93,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Myocardium",
      "func": "Thick middle layer of cardiac muscle that contracts to pump blood."
    },
    {
      "id": 64,
      "x": 65.85,
      "y": 58.62,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Epicardium (visceral serous pericardium)",
      "func": "Outermost layer of the heart wall \u2014 the visceral layer of the serous pericardium."
    },
    {
      "id": 65,
      "x": 70.73,
      "y": 24.14,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pericardial cavity",
      "func": "Fluid-filled space between the visceral and parietal serous layers that lets the heart beat with little friction."
    },
    {
      "id": 66,
      "x": 78.05,
      "y": 44.83,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Parietal layer of serous pericardium",
      "func": "Serous membrane lining the fibrous pericardium; forms the outer wall of the pericardial cavity."
    },
    {
      "id": 67,
      "x": 87.8,
      "y": 31.03,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Fibrous pericardium",
      "func": "Tough outer connective-tissue sac that anchors the heart and keeps it from overfilling."
    }
  ],
  "resp_overview": [
    {
      "id": 68,
      "x": 40.48,
      "y": 15.29,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nasal cavity",
      "func": "Warms, humidifies, and filters incoming air before it travels to the lungs."
    },
    {
      "id": 69,
      "x": 64.29,
      "y": 25.88,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pharynx",
      "func": "Shared passageway that conducts air (and, in its lower parts, food) toward the larynx and esophagus."
    },
    {
      "id": 70,
      "x": 59.52,
      "y": 37.65,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Larynx",
      "func": "Voice box; routes air into the trachea, produces sound, and keeps food out of the airway."
    },
    {
      "id": 71,
      "x": 71.43,
      "y": 42.35,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Trachea",
      "func": "Windpipe; conducts air between the larynx and the bronchi."
    },
    {
      "id": 72,
      "x": 71.43,
      "y": 57.65,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Main (primary) bronchus",
      "func": "Conducts air from the trachea into a lung."
    },
    {
      "id": 73,
      "x": 45.24,
      "y": 65.88,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Lung",
      "func": "Organ of gas exchange where oxygen enters the blood and carbon dioxide leaves it."
    },
    {
      "id": 74,
      "x": 69.05,
      "y": 82.35,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Diaphragm",
      "func": "Main muscle of inspiration; contracts and flattens to draw air into the lungs."
    }
  ],
  "resp_upper": [
    {
      "id": 75,
      "x": 80.43,
      "y": 18.09,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nasal conchae",
      "func": "Scroll-like projections that warm, humidify, and filter air by increasing the nasal surface area."
    },
    {
      "id": 76,
      "x": 65.22,
      "y": 14.89,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nasal meatus",
      "func": "Air passages beneath each concha that channel airflow through the nasal cavity."
    },
    {
      "id": 77,
      "x": 89.13,
      "y": 27.66,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nasal vestibule",
      "func": "Entrance to the nasal cavity, just inside the nostril."
    },
    {
      "id": 78,
      "x": 95.65,
      "y": 29.79,
      "labelDx": 0,
      "labelDy": 5,
      "word": "External nares (nostril)",
      "func": "The nostrils \u2014 the openings where air enters the nasal cavity."
    },
    {
      "id": 79,
      "x": 82.61,
      "y": 31.91,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Hard palate",
      "func": "Bony front of the roof of the mouth that separates the oral and nasal cavities."
    },
    {
      "id": 80,
      "x": 76.09,
      "y": 36.17,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Soft palate",
      "func": "Muscular back of the palate; rises to block the nasopharynx during swallowing."
    },
    {
      "id": 81,
      "x": 60.87,
      "y": 40.43,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Uvula",
      "func": "Fleshy tip of the soft palate that helps close off the nasopharynx during swallowing."
    },
    {
      "id": 82,
      "x": 47.83,
      "y": 24.47,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Opening of auditory (pharyngotympanic) tube",
      "func": "Opening that equalizes air pressure between the middle ear and the nasopharynx."
    },
    {
      "id": 83,
      "x": 43.48,
      "y": 28.72,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Nasopharynx",
      "func": "Uppermost part of the pharynx behind the nasal cavity; an air-only passage."
    },
    {
      "id": 84,
      "x": 50.0,
      "y": 45.74,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Oropharynx",
      "func": "Middle part of the pharynx behind the mouth; a shared passage for air and food."
    },
    {
      "id": 85,
      "x": 54.35,
      "y": 53.19,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Laryngopharynx",
      "func": "Lowest part of the pharynx; a shared passage opening into the larynx and esophagus."
    },
    {
      "id": 86,
      "x": 65.22,
      "y": 50.0,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Epiglottis",
      "func": "Flap of cartilage that covers the laryngeal opening during swallowing to keep food out of the airway."
    },
    {
      "id": 87,
      "x": 60.87,
      "y": 62.77,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Vocal fold (vocal cords)",
      "func": "Folds in the larynx that vibrate as air passes to produce sound."
    },
    {
      "id": 88,
      "x": 54.35,
      "y": 63.83,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Glottis",
      "func": "The vocal folds together with the opening between them (rima glottidis) through which air passes to make sound."
    },
    {
      "id": 89,
      "x": 67.39,
      "y": 60.64,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Thyroid cartilage",
      "func": "Largest laryngeal cartilage; forms the 'Adam's apple' and protects the vocal cords."
    },
    {
      "id": 90,
      "x": 65.22,
      "y": 67.02,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Cricoid cartilage",
      "func": "Ring-shaped cartilage that supports the larynx and connects it to the trachea."
    },
    {
      "id": 91,
      "x": 58.7,
      "y": 88.3,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Trachea",
      "func": "Windpipe; conducts air between the larynx and the bronchi."
    }
  ],
  "resp_larynx": [
    {
      "id": 92,
      "x": 33.33,
      "y": 9.76,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Epiglottis",
      "func": "Flap of cartilage that folds over the airway during swallowing to keep food out of the larynx."
    },
    {
      "id": 93,
      "x": 26.67,
      "y": 34.15,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Thyroid cartilage",
      "func": "Largest laryngeal cartilage ('Adam's apple'); protects the vocal cords."
    },
    {
      "id": 94,
      "x": 26.67,
      "y": 63.41,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Cricothyroid ligament",
      "func": "Connects the thyroid cartilage to the cricoid cartilage below it."
    },
    {
      "id": 95,
      "x": 36.67,
      "y": 73.17,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Cricoid cartilage",
      "func": "Ring-shaped cartilage at the base of the larynx that connects it to the trachea."
    },
    {
      "id": 96,
      "x": 40.0,
      "y": 82.93,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tracheal cartilages",
      "func": "C-shaped rings of cartilage that hold the trachea open."
    }
  ],
  "resp_lungs": [
    {
      "id": 97,
      "x": 50.0,
      "y": 7.87,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Trachea",
      "func": "Windpipe; conducts air toward the lungs and divides at the carina."
    },
    {
      "id": 98,
      "x": 54.17,
      "y": 32.58,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Carina",
      "func": "Ridge where the trachea splits into the two main bronchi; a sensitive cough trigger."
    },
    {
      "id": 99,
      "x": 61.11,
      "y": 35.96,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Main (primary) bronchus",
      "func": "Conducts air from the trachea into a lung."
    },
    {
      "id": 100,
      "x": 72.22,
      "y": 46.07,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Lobar (secondary) bronchus",
      "func": "Branch of the main bronchus that supplies one lobe of a lung."
    },
    {
      "id": 101,
      "x": 76.39,
      "y": 61.8,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Segmental (tertiary) bronchus",
      "func": "Branch of a lobar bronchus that supplies one bronchopulmonary segment."
    },
    {
      "id": 102,
      "x": 25.0,
      "y": 40.45,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right superior lobe",
      "func": "Upper lobe of the right lung \u2014 the right lung has three lobes."
    },
    {
      "id": 103,
      "x": 25.0,
      "y": 75.28,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right middle lobe",
      "func": "Middle lobe of the right lung; found only on the right side."
    },
    {
      "id": 104,
      "x": 26.39,
      "y": 88.76,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Right inferior lobe",
      "func": "Lower lobe of the right lung."
    },
    {
      "id": 105,
      "x": 70.83,
      "y": 17.98,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left superior lobe",
      "func": "Upper lobe of the left lung \u2014 the left lung has two lobes."
    },
    {
      "id": 106,
      "x": 79.17,
      "y": 89.89,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Left inferior lobe",
      "func": "Lower lobe of the left lung."
    }
  ],
  "resp_alveoli": [
    {
      "id": 107,
      "x": 37.93,
      "y": 62.12,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Respiratory bronchiole",
      "func": "Smallest airway; leads air to the alveolar ducts and has a few alveoli of its own."
    },
    {
      "id": 108,
      "x": 32.76,
      "y": 33.33,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Alveolar duct / sac",
      "func": "Passage that channels air from the bronchiole into clusters of alveoli."
    },
    {
      "id": 109,
      "x": 93.1,
      "y": 65.15,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Alveolus",
      "func": "Tiny air sac where gas exchange occurs between the air and the blood."
    },
    {
      "id": 110,
      "x": 44.83,
      "y": 75.76,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pulmonary arteriole",
      "func": "Small vessel that delivers deoxygenated blood to the alveolar capillaries."
    },
    {
      "id": 111,
      "x": 36.21,
      "y": 89.39,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pulmonary venule",
      "func": "Small vessel that carries freshly oxygenated blood away from the alveoli."
    }
  ],
  "resp_trachea_histo": [
    {
      "id": 112,
      "x": 69.23,
      "y": 36.99,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pseudostratified ciliated columnar epithelium",
      "func": "Lining of the trachea that traps inhaled debris in mucus and sweeps it upward."
    },
    {
      "id": 113,
      "x": 47.44,
      "y": 39.73,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Cilia",
      "func": "Hair-like projections that sweep mucus and trapped particles up toward the throat."
    },
    {
      "id": 114,
      "x": 19.23,
      "y": 23.29,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Goblet cell",
      "func": "Secretes the mucus that traps inhaled dust and microbes."
    },
    {
      "id": 115,
      "x": 32.05,
      "y": 56.16,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Mucosa",
      "func": "Inner lining of the trachea \u2014 the epithelium plus the underlying lamina propria (loose connective tissue)."
    },
    {
      "id": 116,
      "x": 91.03,
      "y": 76.71,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Tracheal (seromucous) glands",
      "func": "Glands in the submucosa that secrete watery mucus onto the tracheal lining."
    }
  ],
  "resp_pleura": [
    {
      "id": 117,
      "x": 74.19,
      "y": 48.57,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Parietal pleura",
      "func": "Serous membrane lining the chest wall \u2014 the outer pleural layer."
    },
    {
      "id": 118,
      "x": 67.74,
      "y": 65.71,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Pleural cavity",
      "func": "Fluid-filled space between the two pleurae that reduces friction during breathing."
    },
    {
      "id": 119,
      "x": 64.52,
      "y": 85.71,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Visceral pleura",
      "func": "Serous membrane covering the surface of the lung \u2014 the inner pleural layer."
    }
  ],
  "resp_muscles": [
    {
      "id": 120,
      "x": 25.0,
      "y": 28.57,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Intercostal muscles",
      "func": "Muscles between the ribs that raise and lower the rib cage during breathing."
    },
    {
      "id": 121,
      "x": 57.5,
      "y": 78.57,
      "labelDx": 0,
      "labelDy": 5,
      "word": "Diaphragm",
      "func": "Main muscle of inspiration; contracts and flattens to draw air into the lungs."
    }
  ]
};

// Image credits, carried over from the practical. Several sources are
// CC BY / CC BY-SA, which require attribution however the app is used.
const CREDITS = [
  {
    "what": "Respiratory diagrams \u2014 system overview, upper airway, larynx, lungs & bronchial tree, trachea histology, and pleurae",
    "src": "OpenStax, <em>Anatomy and Physiology</em>",
    "lic": "CC BY 4.0",
    "url": "https://openstax.org/details/books/anatomy-and-physiology"
  },
  {
    "what": "Heart wall &amp; pericardium diagram",
    "src": "OpenStax College, <em>Anatomy &amp; Physiology</em> (via Wikimedia Commons, &ldquo;2004 Heart Wall&rdquo;)",
    "lic": "CC BY 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:2004_Heart_Wall.jpg"
  },
  {
    "what": "Cardiac muscle histology micrograph (slide&nbsp;45)",
    "src": "RWhitwam, Wikimedia Commons (&ldquo;Cardiac muscle 305&rdquo;, labels cropped)",
    "lic": "CC BY-SA 4.0",
    "url": "https://commons.wikimedia.org/wiki/File:Cardiac_muscle_305.png"
  },
  {
    "what": "Alveolus / lung-histology diagram",
    "src": "Wikimedia Commons (original labels cropped) \u2014 specific file &amp; author to be confirmed",
    "lic": "likely CC BY-SA",
    "url": ""
  },
  {
    "what": "Histology micrographs \u2014 blood formed elements (slide&nbsp;16), artery/vein/nerve wall (slide&nbsp;3), cardiac muscle (slide&nbsp;45)",
    "src": "BIOL&nbsp;40B lab slide collection",
    "lic": "course materials",
    "url": ""
  },
  {
    "what": "Heart illustrations \u2014 internal section, external surface, valves, conduction system",
    "src": "Source not recorded. If you hold the rights to one of these figures, please get in touch and it will be credited or removed on request.",
    "lic": "",
    "url": ""
  }
];
