#!/usr/bin/env python3
"""Generate the BIOL 40B Lab Exam 2 labeling app from the Practical 2 data.

Reads the verified IMAGES / Q / STATIONS tables out of the mock-practical
build script, bakes each image's crop + label-covers into a real JPEG, and
converts every pin coordinate from "% of original" into "% of the cropped
image" so the labeling engine can use them directly.

Output: images/, data.js, index.html.  Run: python3 gen.py
"""
import json
import shutil
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
PRACTICAL = Path.home() / "Desktop" / "Practical 2 materials" / "build"
MAX_W = 1400          # generous: students zoom in on histology slides
JPEG_QUALITY = 88

sys.path.insert(0, str(PRACTICAL))
import build  # noqa: E402  (also regenerates its own practical.html; harmless)


def pct_box(w, h, box):
    """[x,y,w,h] as % of the original -> pixel box (l, t, r, b)."""
    x, y, bw, bh = box
    return (round(x / 100 * w), round(y / 100 * h),
            round((x + bw) / 100 * w), round((y + bh) / 100 * h))


def bake(name, meta):
    """Paint covers, crop, downscale. Returns the output filename."""
    src = PRACTICAL / "images" / meta["file"]
    im = Image.open(src)
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        bg = Image.new("RGB", im.size, (255, 255, 255))
        bg.paste(im, mask=im.split()[-1])
        im = bg
    else:
        im = im.convert("RGB")

    w, h = im.size
    # Covers hide stray printed labels that would give the answer away.
    if meta["covers"]:
        from PIL import ImageDraw
        d = ImageDraw.Draw(im)
        for c in meta["covers"]:
            d.rectangle(pct_box(w, h, c), fill=(255, 255, 255))

    im = im.crop(pct_box(w, h, meta["crop"]))
    if im.width > MAX_W:
        im = im.resize((MAX_W, round(im.height * MAX_W / im.width)), Image.LANCZOS)

    out = f"{name}.jpg"
    im.save(HERE / "images" / out, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    return out, im.size


def to_crop_space(x, y, crop):
    """Pin at (x,y) % of ORIGINAL -> % of the cropped image."""
    cx, cy, cw, ch = crop
    return round((x - cx) / cw * 100, 2), round((y - cy) / ch * 100, 2)


def main():
    (HERE / "images").mkdir(exist_ok=True)
    for f in (HERE / "images").glob("*.jpg"):
        f.unlink()

    pins_by_img = {}
    for img, x, y, disp, _answers, func, _blood in build.Q:
        pins_by_img.setdefault(img, []).append((x, y, disp, func))

    image_data, preset_keys, dropped = {}, {}, []
    marker_id = 0

    for name, meta in build.IMAGES.items():
        fname, (pw, ph) = bake(name, meta)
        crop = meta["crop"]

        words, markers = [], []
        for x, y, disp, func in pins_by_img.get(name, []):
            nx, ny = to_crop_space(x, y, crop)
            if not (0 <= nx <= 100 and 0 <= ny <= 100):
                # Pin sits outside the visible crop -- would be unplaceable.
                dropped.append((name, disp, nx, ny))
                continue
            marker_id += 1
            words.append(disp)
            markers.append({
                "id": marker_id, "x": nx, "y": ny,
                "labelDx": 0, "labelDy": 5,
                "word": disp, "func": func,
            })

        image_data[name] = {
            "src": f"images/{fname}",
            "title": build.STATIONS[name],
            "caption": meta["caption"],
            "words": sorted(words, key=str.lower),
            "size": [pw, ph],
        }
        preset_keys[name] = markers

    # build.py's credit for the unsourced heart figures is an internal TODO
    # ("confirm ... before public distribution"). On a public page that should
    # read as an honest notice with a route to correction, not a note-to-self.
    credits = [dict(c) for c in build.CREDITS]
    for c in credits:
        if "not individually recorded" in c["src"]:
            c["src"] = ("Source not recorded. If you hold the rights to one of "
                        "these figures, please get in touch and it will be "
                        "credited or removed on request.")

    order = list(build.IMAGES.keys())
    data_js = (
        "// GENERATED BY gen.py -- do not hand-edit; edit build.py data and re-run.\n"
        f"const IMAGE_ORDER = {json.dumps(order, indent=2)};\n\n"
        f"const IMAGE_DATA = {json.dumps(image_data, indent=2)};\n\n"
        "// Pre-verified answer key. Loaded on first run; the teacher can\n"
        "// re-pin anything and Save to override it in localStorage.\n"
        f"const PRESET_KEYS = {json.dumps(preset_keys, indent=2)};\n\n"
        "// Image credits, carried over from the practical. Several sources are\n"
        "// CC BY / CC BY-SA, which require attribution however the app is used.\n"
        f"const CREDITS = {json.dumps(credits, indent=2)};\n"
    )
    (HERE / "data.js").write_text(data_js)

    tabs = "\n".join(
        f'            <button class="tab{" active" if i == 0 else ""}" '
        f'data-image="{k}">{build.STATIONS[k].split(chr(183), 1)[1].strip()}</button>'
        for i, k in enumerate(order)
    )
    tpl = (HERE / "index_template.html").read_text()
    (HERE / "index.html").write_text(tpl.replace("<!--__TABS__-->", tabs))

    total = sum(len(v) for v in preset_keys.values())
    kb = sum(f.stat().st_size for f in (HERE / "images").glob("*.jpg")) / 1024
    print(f"images: {len(image_data)}  ({kb:.0f} KB)")
    print(f"pre-pinned terms: {total}")
    if dropped:
        print(f"\nWARNING - {len(dropped)} pin(s) fell outside their crop and were dropped:")
        for name, disp, nx, ny in dropped:
            print(f"  {name}: {disp} -> ({nx}, {ny})")


if __name__ == "__main__":
    main()
